apiVersion: v1
kind: ConfigMap
metadata:
  # Este es el nombre del archivo de configuración que realmente importa,
  # no el nombre que le hemos puesto al archivo.
  # Este nombre lo usaré luego para hacer referencia a mis key-values pairs
  name: postgres-config
data:
  DB_NAME: postgres
  # DB_HOST es el nombre del servidor donde esta el servicio de la BD.
  # Todavía no lo tenemos definido, y eso es correcto, pero sabemos que lo vamos a tener
  # dentro de algo que se llama postgres-service. Recordar que un servicio ya tiene una
  # dirección de IP fija
  DB_HOST: postgres-service
  # Tiene que ser manejado como un string.
  DB_PORT: '5432'
